Added basic types: string, IPv4 address, IPv6 address.
ietf-tapswg/api-drafts pull request #1207
Opened 2023-06-07 15:56 UTC by mwelzl

Closes #1183

2023-06-15 15:18 UTC, philsbln requested changes
I have three asks for this PR:
- Please add String/IPv6Address/IPv4Address a little further up, as we sorted simple types first, collection/composed types later
- Do we need to restrict ourselves to alphanumeric strings or shouldn't we ask for the default string type of the implementation, preferably unicode-compatible
- Separate types for IPv4 and IPv6 or better have a type that catches both?

2023-06-23 19:06 UTC, mwelzl commented
Done; better now?  @philsbln please check.

2023-06-24 00:05 UTC, tfpauly approved these changes

2023-06-24 00:05 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +  language, e.g. unicode.
```suggestion
  language, e.g. UTF-8.
```

maybe this?

2023-06-26 07:29 UTC, philsbln approved these changes
Yes, perfect. Thank you very much!

Now, we need to make Specifying Endpoint consistent to that…  made an Issue #1210 for that and will file a PR too

2023-07-06 19:44 UTC, merged