Change hi<->lo priority
ietf-tapswg/api-drafts pull request #1400
Opened 2023-10-03 07:13 UTC by gorryfair

Suggested to align with other IETF specs. Closes 1378 ifhen merged.

2023-10-03 07:23 UTC, gorryfair commented
No mention of the priority order was found in the arch and implementation specs.

2023-10-10 11:51 UTC, mwelzl requested changes
There is an example that you changed, but I think it was right before. I think this is what happened:
Version 1 which we once had: this was written, and correct.
Version 2, where we flipped the order: this was overlooked, and therefore wrong.
This PRs version, where we flip the order again: now this previously-wrong text from version 2  automatically becomes correct again.

2023-10-10 11:51 UTC, mwelzl commented on draft-ietf-taps-interface.md
> +(e.g., transport-layer flow control), a priority 0 Message on a priority 1
```suggestion
(e.g., transport-layer flow control), a priority 1 Message on a priority 0
```

2023-10-10 11:51 UTC, mwelzl commented on draft-ietf-taps-interface.md
> +Connection will be sent before a priority 1 Message on a priority 0
```suggestion
Connection will be sent before a priority 0 Message on a priority 1
```

2023-10-10 16:26 UTC, tfpauly requested changes

2023-10-10 16:26 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +higher Priority values. Capacity will be shared among these Connections according to
```suggestion
numerically lower Priority values will be prioritized over sends on Connections that have
numerically  higher Priority values. Capacity will be shared among these Connections according to
```

2023-10-10 16:26 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +Connection Group. A lower value reflects a higher priority. It has no effect
```suggestion
Connection Group. A numerically lower value reflects a higher priority. It has no effect
```

2023-10-10 16:26 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +same Connection. A lower value represents a higher priority.
```suggestion
same Connection. A numerically lower value represents a higher priority.
```

2023-10-10 19:42 UTC, mwelzl commented
@tfpauly - great suggestions!  I felt uneasy about these "lower" / "higher" words but didn't quite know what to do... I think putting "numerically" there makes it super clear.

2023-10-16 14:56 UTC, mwelzl commented on draft-ietf-taps-interface.md
> +numerically  higher Priority values. Capacity will be shared among these Connections according to
```suggestion
numerically higher Priority values. Capacity will be shared among these Connections according to
```

2023-10-16 23:24 UTC, tfpauly approved these changes

2023-10-16 23:27 UTC, merged