Make Transport Property Names more strict (and case-insenstitive)
ietf-tapswg/api-drafts pull request #1404
Opened 2023-10-11 07:21 UTC by philsbln

alternative to #1402
closes #1338

2023-10-11 10:38 UTC, mwelzl requested changes
One suggestion

2023-10-11 10:38 UTC, mwelzl commented on draft-ietf-taps-interface.md
> +The underscore `_` is only allowed at the first position.
```suggestion
```

I don't understand the point of this rule, and it even contradicts what you say below about snake_case. The next sentence, "They must start with a letter or an underscore" seems good enough.

2023-10-11 10:38 UTC, mwelzl commented on draft-ietf-taps-interface.md
> +Implementations may transpose Transport Property Names into snake_case or PascalCase to blend into the language environment.
I note that this is pretty strict... we don't know how styles of future languages will be?  But I like it nevertheless. If we allow "any" kind of transposition, we make porting applications harder.

2023-10-11 12:37 UTC, mwelzl commented on draft-ietf-taps-interface.md
> +The underscore `_` is only allowed at the first position.
Aha, I see...
```suggestion
The underscore `_` is only allowed at the first position (with the exception of transposing into snake_case, see below).
```

2023-10-12 09:14 UTC, mwelzl approved these changes

2023-10-17 15:26 UTC, mwelzl commented on draft-ietf-taps-interface.md
> +letters `a-z` / `A-Z`, digits `0-9`, the hyphen `-`.
```suggestion
letters `a-z` / `A-Z`, digits `0-9`, the hyphen `-` and the underscore `_`.
```

2023-10-17 15:34 UTC, tfpauly requested changes

2023-10-20 09:49 UTC, gorryfair approved these changes
I like this line of approach - subject to addressing current review comments

2023-10-20 15:21 UTC, mwelzl commented
I think this minimalistic and much less strict angle reflects what was agreed on at the interim. About time to merge it, I believe.

2023-10-20 15:21 UTC, merged