Protocol identifiers are strings, listed in the API doc.
ietf-tapswg/api-drafts pull request #1408
Opened 2023-10-11 11:53 UTC by mwelzl

Closes #1332
Closes #1333

2023-10-12 07:33 UTC, gorryfair approved these changes

2023-10-17 15:46 UTC, tfpauly requested changes

2023-10-17 15:46 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +this automated selection could be over-ridden (e.g., for testing or
```suggestion
this automated selection could be overridden (e.g., for testing or
```

2023-10-17 15:46 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +contain a list of selectable protocol specifiers.
```suggestion
To scope an alias to apply conditionally to a specific transport
protocol (such as defining an alternate port to use when QUIC
is selected, as opposed to TCP), an alias Endpoint can be
associated with a protocol identifier. Protocol identifiers are
objects or enumeration values provided by the Transport
Services API, which will vary based on which protocols are
implemented in a particular system.

specify a protocol specifier. Protocol specifiers
are strings where slashes separate protocol names. The API
documentation of a Transport Services system implementation ought to
contain a list of selectable protocol specifiers.
```

2023-10-17 15:46 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +debugging purposes).
```suggestion
```

Suggest removing this paragraph, since this is specific to aliases.

2023-10-17 15:48 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +debugging purposes).
```suggestion
```

2023-10-17 15:51 UTC, merged