keepAliveTimeout: introduce `System default`
ietf-tapswg/api-drafts pull request #1444
Opened 2023-11-01 15:15 UTC by mwelzl

This partially addresses #1428
Please see the discussion there for the rationale behind this.

2023-11-01 17:40 UTC, philsbln approved these changes
Works for me except that I really prefer a single-word here

2023-11-01 17:40 UTC, philsbln commented on draft-ietf-taps-interface.md
> +: Numeric (non-negative) or `Disabled` or `System default`
I guess having a single-word value makes this more portable…

```suggestion
: Numeric (non-negative) or `Disabled` or `Default`
```

2023-11-01 17:40 UTC, philsbln commented on draft-ietf-taps-interface.md
> +: `System default`
```suggestion
: `Default`
```

2023-11-01 17:40 UTC, philsbln commented on draft-ietf-taps-interface.md
> +could express `Disabled` and `System default` in an environment-typical way, e.g., as a Union type or special value. Choosing `System default` is a hint to the Transport Services system that it shoul
```suggestion
could express `Disabled` and `Default` in an environment-typical way, e.g., as a Union type or special value. Choosing `Default` is a hint to the Transport Services system that it should
```

2023-11-01 18:57 UTC, mwelzl commented
How about SysDefault instead of Default? It's a single word, yet avoids the somewhat ugly:
"Default: default"

2023-11-08 12:00 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +: `SysDefault`
The default for keepalives should be off.

2023-11-08 12:00 UTC, tfpauly commented
I think we should close as not to be fixed

2023-11-08 12:03 UTC, tfpauly requested changes
Let's discuss and maybe close

2023-11-08 13:51 UTC, philsbln requested changes
After discussion, I second @tfpauly

2023-11-09 09:39 UTC, closed without merging