Clarify multiple Local/remote endpoints
ietf-tapswg/api-drafts pull request #1447
Opened 2023-11-04 13:33 UTC by philsbln

Replace the over-specific definitions with racing compatible equivalents without mentioning racing.

Fixes #1339 
Fixes #1340

2023-11-04 13:43 UTC, gorryfair commented on draft-ietf-taps-interface.md
> +For example, their Endpoint Identifiers might correspond to different interfaces on a multi-homed
I do not understand /eliable/ ?

2023-11-04 14:34 UTC, mwelzl reviewed
Just a nit

Else, I see... you say the system should assume it, instead of saying it should represent - makes more sense to me!  but I feel a bit insecure about the whole thing and would want others to take the go/no-go decision on this one.

2023-11-04 14:34 UTC, mwelzl commented on draft-ietf-taps-interface.md
> +the transport system SHOULD assume that all the Remote Endpoints on the
```suggestion
the Transport Services system SHOULD assume that all the Remote Endpoints on the
```

2023-11-08 11:56 UTC, tfpauly requested changes

2023-11-08 11:56 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +For example, their Endpoint Identifiers might correspond to different interfaces on a multi-homed
```suggestion
If more than one Local Endpoint is specified on a Preconnection, then the application
 is indicating that all of the Local Endpoints are eligible to be used for Connections. For
 example, their Endpoint Identifiers might correspond to different interfaces on a multi-homed
```

2023-11-08 11:56 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +the Transport Services system can choose any of them serving the application.
```suggestion
If more than one Remote Endpoint is specified on the Preconnection, the
application is indicating that it expects all of the Remote Endpoints to
offer an equivalent service, and that the Transport Services system can choose
any of them for a Connection.
```

2023-11-08 11:56 UTC, gorryfair approved these changes

2023-11-08 11:56 UTC, tfpauly approved these changes

2023-11-08 12:03 UTC, merged