Add FQDN endpoint identifyer
ietf-tapswg/api-drafts pull request #1464
Opened 2024-01-27 11:44 UTC by philsbln

Add an option to distinguish FQDNs from unqualified HostNames to address concerns from #1460

2024-01-27 12:03 UTC, mwelzl reviewed
"ABSTAIN":

I see, this implements a comment you added to a previous PR.

Is this an improvement or not? I'm not sure - on the one hand, it makes the API bigger, but on the other, it makes the dangers of not using an FQDN somewhat more explicit. That's a bit like our decision to have an "InitiateWithSend" call as opposed to adding a "data" parameter to "Initiate".

There's a design trade-off here, and I'm undecided about what is better.

Also, I'm not sure it's a good idea to make such a change that late in the process.

2024-01-29 15:56 UTC, tfpauly requested changes

2024-01-29 15:56 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +- HostName (string that gets qualified while resolving, e.g., using DNS search domains):
```suggestion
- HostName (a string, which SHOULD be a Fully Qualified Domain Name):
```

2024-01-29 15:56 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +domain names (FQDNs) instead. Not providing an FQDN will result in the Transport Services Implementation
```suggestion
Applications creating Endpoint objects using `WithHostName` SHOULD provide fully-qualified
domain names (FQDNs). Not providing an FQDN will result in the Transport Services Implementation
```

2024-01-29 17:05 UTC, mwelzl commented
Can we close this?

I think the consensus was that it would only be ok to do with the changes suggested by @tfpauly , but then this does not really add any extra functionality since names are already specified to be FQDN's with a SHOULD.

2024-01-29 17:44 UTC, tfpauly commented
I think this is fine to close

2024-01-30 12:53 UTC, philsbln commented
With the changes discussed, it does not really add any value but adds changes to the next review phase

2024-01-30 12:53 UTC, closed without merging