Bring the multipath text in line with the API
ietf-tapswg/api-drafts pull request #742
Opened 2021-03-25 12:11 UTC by mwelzl

Closes #704.

Note, the change to the API draft here is a purely editorial detail that I fixed here in passing: the multipath selection property was renamed and this fixes the text referring to it.

2021-03-25 19:04 UTC, martinduke approved these changes

2021-03-25 19:35 UTC, abrunstrom requested changes
Not sure this is what we discussed, but I like it better so I am happy with the update, thanks! Noticed two small things to update on the "old" text.

2021-03-25 19:35 UTC, abrunstrom commented on draft-ietf-taps-impl.md
> +In case of Pooled Connections {{pooled-connections}}, the Transport Services implementation may add connections over new paths or different protocols to the pool if permissible based on the multipath
"may add connections over new paths or different protocols", I think the "or different protocols" part has nothing to do with multipath and should be removed.

2021-03-25 19:35 UTC, abrunstrom commented on draft-ietf-taps-impl.md
> +When a path change occurs, e.g., when the IP address of an interface changes or a new interface becomes available, the Transport Services implementation is responsible for notifying the application o
notifying the application of the change. --> notifying the Protocol Instance of the change.

2021-03-26 08:39 UTC, mwelzl commented
"what we discussed" - you mean in #704, where I say that I stumbled over a sentence? This PR does update that sentence (simply removing "with migration support" from it because any multipath protocol can do that).

2021-03-26 15:10 UTC, tfpauly approved these changes
Looks good to me!

2021-03-26 15:58 UTC, abrunstrom commented
> "what we discussed" - you mean in #704, where I say that I stumbled over a sentence? 

no, i meant what we discussed at the interim about using the handover, interactive, aggregate terminology. but i saw that this was not so easily done and we are all happy with your solution, so all good :)

2021-03-26 15:59 UTC, abrunstrom approved these changes
Thanks for fixing the nits!

2021-04-09 15:08 UTC, merged