Clarify Events upon various close / abort calls.
ietf-tapswg/api-drafts pull request #771
Opened 2021-04-12 12:21 UTC by mwelzl

(Gracefully,  he he  :)  ) Closes #761.

2021-04-12 15:00 UTC, martinduke requested changes
From this text I still don't understand when TAPS sends Closed<>. Is it (1) in response to a Close(), when all data has been delivered, or when the remote endpoint has closed?

Is it the first of these two events to occur?

2021-04-12 15:34 UTC, mwelzl commented
Ah, I see, sorry!  I just committed a fix; is it better now?

The new text describing the Closed Event is only this:

> The Closed Event informs the application that a Close Action has successfully completed, or that the Remote Endpoint has closed the Connection.

2021-04-18 19:59 UTC, tfpauly approved these changes

2021-05-03 17:50 UTC, martinduke commented
Still, it says that this means either everything has been delivered, or the peer has closed the connection. Does this mean I would get two events on a clean TCP close?

2021-05-05 06:26 UTC, mwelzl commented
No, one: because the Connection was "closed". Case 1 in the sentence, where it says "Close Action", refers to the call made by the local application - the application made the call, and it terminated correctly. The remote close is the other case leading to a Connection being closed - since it doesn't say "abort" or "forcefully closed", it's the same thing, a graceful close. So... there are two reasons leading to one thing happening, and when that one thing is over, the applications gets an Event.

I'm not sure how you read this differently... it's clear to me. Would this variant help?

> The Closed Event informs the application that the Connection has been closed - either because a Close Action call has successfully completed, or because the Remote Endpoint has closed the Connection.

2021-05-05 15:53 UTC, martinduke commented
I've read this again, and I think it's OK.

2021-05-07 13:47 UTC, philsbln requested changes
I am still missing a clear statement whether a developer can rely on eventually receiving either a Closed event or a ConnectionError event per Connection.

2021-05-07 15:42 UTC, tfpauly commented
Can we explain in the start of the connection termination section a specific list of the different end states/events a connection can have? (Either Closed or ConnectionError, for example).

2021-05-07 15:48 UTC, mwelzl commented
Note to self: also add some introductory text for this section as requested by Anna elsewhere

2021-05-20 09:56 UTC, mwelzl commented
Done - please take a look at the new intro.

2021-05-20 11:13 UTC, gorryfair reviewed
A couple of minor queries

2021-05-20 11:13 UTC, gorryfair commented on draft-ietf-taps-interface.md
> +or the ConnectionError Event. A local call of the Abort Action will cause the Connection to send
is this /to either send/ ... I'm unsure what the "or" refers to.

2021-05-20 11:13 UTC, gorryfair commented on draft-ietf-taps-interface.md
why /indeed/ in /will indeed be signaled./?

2021-05-20 11:13 UTC, gorryfair commented on draft-ietf-taps-interface.md
Similarly, should this /will be signalled/?

2021-06-11 16:22 UTC, merged