Fixes around Clone and entanglement
ietf-tapswg/api-drafts pull request #794
Opened 2021-04-15 12:20 UTC by mwelzl

Closes #774. Closes #788.
This changes the use of the term "entanglement" as discussed in #774, and moves some text around in this section for better clarity and less repetition. Also, addressing #788, it introduces a framer as an optional parameter to the Clone call.

2021-04-16 16:17 UTC, gorryfair approved these changes
This resolves the issues with the entangled wording, many thanks

2021-04-23 09:03 UTC, gorryfair requested changes
I like the way this is going, but I have suggestions for various changes that might improve this.

2021-04-23 09:03 UTC, gorryfair commented on draft-ietf-taps-interface.md
> +change this Connection Property for all other Connections in the Connection Group in the same way.
Suggest: 
/will automatically make the same change to this Connection Property for all other Connections in the Connection Group./

2021-04-23 09:03 UTC, gorryfair commented on draft-ietf-taps-interface.md
> +`Connection Priority` on one Connection does not change it on the
/changing/in this case, a later change to the/

2021-04-23 09:03 UTC, gorryfair commented on draft-ietf-taps-interface.md
> +A new Connection created by Clone can get a framer assigned via the optional
/get/have/
and 
/framer/Message Framer/

2021-04-23 09:03 UTC, gorryfair commented on draft-ietf-taps-interface.md
> +multiple such connections being opened instead of multi-streaming,
/multiple such connections being opened/the opening of multiple such connections,/

2021-04-23 12:19 UTC, mwelzl commented
@gorryfair I incorporated all of your suggestions, thanks!

2021-04-23 13:08 UTC, gorryfair approved these changes
Looks good to me.

2021-05-04 14:38 UTC, merged