Not unreliable, but no reliability guarentees.
ietf-tapswg/api-drafts pull request #837
Opened 2021-05-19 13:21 UTC by gorryfair

Not requiring things to be unreliable, but allow no reliability guarentees.
and /throw/generate/

2021-05-19 22:13 UTC, abrunstrom approved these changes
LGTM, only one possible small change suggested.

2021-05-19 22:13 UTC, abrunstrom commented on draft-ietf-taps-interface.md
> +* "Reliably transfer data, with congestion control", "Reliably transfer a message, with congestion control" and "Transfer a message without reliability":
Perhaps "without reliability guarantees"?

2021-05-20 08:28 UTC, mwelzl requested changes
LGTM except for one detail (I made a suggestion)

2021-05-20 08:28 UTC, mwelzl commented on draft-ietf-taps-interface.md
> +* "Reliably transfer data, with congestion control", "Reliably transfer a message, with congestion control" and "Transfer a message without reliability guarantees":
```suggestion
* "Reliably transfer data, with congestion control", "Reliably transfer a message, with congestion control" and "Unreliably transfer a message":
```

Like it or not, but this is a reference to a specific term from RFC 8923, and should therefore be kept as it is. The point of this appendix is to enable back-tracking to the original spec, via 8923 => 8303 or 8304.

2021-05-26 11:42 UTC, merged