Endpoints SHOULD/MAY for Preconnection
ietf-tapswg/api-drafts pull request #974
Opened 2021-12-09 03:13 UTC by seanturner

Closes #973.

2021-12-09 11:39 UTC, gorryfair reviewed
I thought this was needed for the preconnection to be acceptable, so I'm not sure about SHOULD. To me this is either required for the preconnection, or this is a MAY.

2021-12-09 16:38 UTC, tfpauly requested changes
I don't think this change is necessarily correct. The logic is:

- If Listener: MUST have local endpoint, MAY have remote
- If initiator: MUST have remote endpoint, MAY have local

2021-12-09 16:38 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +At least one Local Endpoint SHUOLD be specified if the Preconnection is used to Listen()
```suggestion
At least one Local Endpoint SHOULD be specified if the Preconnection is used to Listen()
```

2022-02-02 16:20 UTC, tfpauly commented on draft-ietf-taps-interface.md
> +At least one Remote Endpoint SHOULD be specified if the Preconnection is used
```suggestion
At least one Remote Endpoint MUST be specified if the Preconnection is used
```
```suggestion
At least one Remote Endpoint SHOULD be specified if the Preconnection is used
```

2022-02-02 16:21 UTC, tfpauly commented
Interim discussion: leave as-is.

2022-02-02 16:21 UTC, closed without merging